FROM openjdk:17
COPY spring-petclinic app.jar
# COPY src /App/src/
# WORKDIR /App/
CMD "java" "-jar" "/app.jar"

# COPY app/build/lib/* build/lib/

# COPY app/build/libs/app.jar build/

# WORKDIR /app/build
# ENTRYPOINT java -jar app.jar
